name: Streamlit Keep Alive

on:
  schedule:
    # 每 10 小时自动运行一次，确保在 12 小时休眠到期前强行唤醒并重构容器
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许您在 GitHub 页面上手动点击运行测试

permissions:
  contents: write # 自动赋予工作流推送到私有仓库的权限

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Push Empty Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # 提交一个完全无内容的空提交
          git commit --allow-empty -m "keep-alive: auto redeploy streamlit"
          git push
